# Primary MongoDB (coupons) - PROD
app.mongodb.primary.uri=mongodb://localhost:27017
app.mongodb.primary.database=coupon_platform

# Secondary MongoDB (e.g. analytics / audit) - PROD
app.mongodb.secondary.uri=mongodb://localhost:27017
app.mongodb.secondary.database=coupon_platform_secondary

